export const top_100 = [
  {"name": "avocado"},
  {"name": "banana"},
  {"name": "sweet potato"},
  {"name": "potato"},
  {"name": "squash"},
  {"name": "carrot"},
  {"name": "peas"},
  {"name": "green beans"},
  {"name": "apple"},
  {"name": "peach"},
  {"name": "pear"},
  {"name": "plum"},
  {"name": "apricot"},
  {"name": "ricotta"},
  {"name": "mango"},
  {"name": "papaya"},
  {"name": "watermelon"},
  {"name": "cantaloupe"},
  {"name": "honeydew"},
  {"name": "blueberries"},
  {"name": "raspberries"},
  {"name": "blackberries"},
  {"name": "strawberries"},
  {"name": "kiwi"},
  {"name": "pineapple"},
  {"name": "orange"},
  {"name": "grapefruit"},
  {"name": "grape"},
  {"name": "cherries"},
  {"name": "cranberries"},
  {"name": "currants"},
  {"name": "fig"},
  {"name": "guava"},
  {"name": "lychee"},
  {"name": "passion fruit"},
  {"name": "persimmon"},
  {"name": "tangerine"},
  {"name": "tomato"},
  {"name": "zucchini"},
  {"name": "cucumber"},
  {"name": "broccoli"},
  {"name": "cauliflower"},
  {"name": "spinach"},
  {"name": "kale"},
  {"name": "collard greens"},
  {"name": "swiss chard"},
  {"name": "beet"},
  {"name": "radicchio"},
  {"name": "lettuce"},
  {"name": "bok choy"},
  {"name": "cabbage"},
  {"name": "brussels sprouts"},
  {"name": "asparagus"},
  {"name": "parsnip"},
  {"name": "eggplant"},
  {"name": "artichoke"},
  {"name": "butternut squash"},
  {"name": "corn"},
  {"name": "cornmeal"},
  {"name": "pumpkin"},
  {"name": "lentil"},
  {"name": "chickpeas"},
  {"name": "black beans"},
  {"name": "kidney beans"},
  {"name": "lima beans"},
  {"name": "edamame"},
  {"name": "quinoa"},
  {"name": "rice"},
  {"name": "oatmeal"},
  {"name": "barley"},
  {"name": "millet"},
  {"name": "wheat"},
  {"name": "couscous"},
  {"name": "farro"},
  {"name": "buckwheat"},
  {"name": "tofu"},
  {"name": "yogurt"},
  {"name": "cheese"},
  {"name": "cottage cheese"},
  {"name": "hummus"},
  {"name": "peanut"},
  {"name": "almond"},
  {"name": "egg"},
  {"name": "chicken"},
  {"name": "turkey"},
  {"name": "beef"},
  {"name": "pork"},
  {"name": "lamb"},
  {"name": "flax seed"},
  {"name": "coconut"},
  {"name": "teff"},
  {"name": "salmon"},
  {"name": "polenta"},
  {"name": "cilantro"},
  {"name": "shrimp"},
  {"name": "sardines"},
  {"name": "mascarpone"},
  {"name": "garlic"},
  {"name": "garbanzo beans"},
  {"name": "bread"},
  {"name": "white beans"},
  {"name": "onion"},
  {"name": "tortillas"},
  {"name": "sorghum"},
  {"name": "starfruit"},
  {"name": "bell pepper"},
  {"name": "lime"},
  {"name": "lemon"},
  {"name": "mushroom"},
  {"name": "cereal"},
  {"name": "mozzarella"},
  {"name": "tuna"},
]
