
    export const top_100 = [
      {"name": "avocado"},
      {"name": "banana"},
      {"name": "sweet potato"},
      {"name": "squash"},
      {"name": "carrots"},
      {"name": "peas"},
      {"name": "green beans"},
      {"name": "applesauce"},
      {"name": "peaches"},
      {"name": "pears"},
      {"name": "plums"},
      {"name": "apricots"},
      {"name": "mango"},
      {"name": "papaya"},
      {"name": "watermelon"},
      {"name": "cantaloupe"},
      {"name": "honeydew"},
      {"name": "blueberries"},
      {"name": "raspberries"},
      {"name": "blackberries"},
      {"name": "strawberries"},
      {"name": "kiwi"},
      {"name": "pineapple"},
      {"name": "oranges"},
      {"name": "grapefruit"},
      {"name": "grapes"},
      {"name": "cherries"},
      {"name": "cranberries"},
      {"name": "currants"},
      {"name": "figs"},
      {"name": "guava"},
      {"name": "lychee"},
      {"name": "passion fruit"},
      {"name": "persimmon"},
      {"name": "tangerines"},
      {"name": "tomatoes"},
      {"name": "zucchini"},
      {"name": "cucumbers"},
      {"name": "broccoli"},
      {"name": "cauliflower"},
      {"name": "spinach"},
      {"name": "kale"},
      {"name": "collard greens"},
      {"name": "swiss chard"},
      {"name": "beet greens"},
      {"name": "arugula"},
      {"name": "endive"},
      {"name": "escarole"},
      {"name": "radicchio"},
      {"name": "romaine lettuce"},
      {"name": "butter lettuce"},
      {"name": "red leaf lettuce"},
      {"name": "green leaf lettuce"},
      {"name": "bok choy"},
      {"name": "cabbage"},
      {"name": "brussels sprouts"},
      {"name": "asparagus"},
      {"name": "celery"},
      {"name": "eggplant"},
      {"name": "artichoke"},
      {"name": "sweet peppers"},
      {"name": "butternut squash"},
      {"name": "acorn squash"},
      {"name": "spaghetti squash"},
      {"name": "pumpkin"},
      {"name": "lentils"},
      {"name": "chickpeas"},
      {"name": "black beans"},
      {"name": "kidney beans"},
      {"name": "lima beans"},
      {"name": "green peas"},
      {"name": "edamame"},
      {"name": "quinoa"},
      {"name": "brown rice"},
      {"name": "oatmeal"},
      {"name": "barley"},
      {"name": "millet"},
      {"name": "whole wheat bread"},
      {"name": "couscous"},
      {"name": "farro"},
      {"name": "buckwheat"},
      {"name": "tofu"},
      {"name": "yogurt"},
      {"name": "cheese"},
      {"name": "cottage cheese"},
      {"name": "hummus"},
      {"name": "peanut butter"},
      {"name": "almond butter"},
      {"name": "cashew butter"},
      {"name": "sunflower seed butter"},
      {"name": "tahini"},
      {"name": "hard-boiled eggs"},
      {"name": "scrambled eggs"},
      {"name": "soft-boiled eggs"},
      {"name": "fish (cod, salmon, tilapia)"},
      {"name": "chicken"},
      {"name": "turkey"},
      {"name": "beef"},
      {"name": "pork"},
      {"name": "lamb"},
      {"name": "venison"}
    ]
  